spring:
  application:
    name: PaymentService

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3436
    url: jdbc:mysql://localhost:3307/microDB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          prefer-ip: true

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9006

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
